@startuml

hide footbox
header CU_AR Flujo Alternativo 1
autonumber

Customer -> VirtualSmartFridge: open() : void
activate VirtualSmartFridge

VirtualSmartFridge -> FridgeDoor : open() : void
activate FridgeDoor

FridgeDoor -> FridgeDoor : increaseTimesOpened() : void
FridgeDoor -> FridgeDoor : startTimer() : void

Customer -> VirtualSmartFridge: put(product : Product) : void
VirtualSmartFridge -> CU_PP_Poner_Producto : <<include>>
|||

@enduml