@startuml

hide footbox
header CU_AR Flujo Alternativo 2
autonumber

Customer -> VirtualSmartFridge: open() : void
activate VirtualSmartFridge

VirtualSmartFridge -> FridgeDoor : open() : void
activate FridgeDoor

FridgeDoor -> FridgeDoor : increaseTimesOpened() : void
FridgeDoor -> FridgeDoor : startTimer() : void

Customer -> VirtualSmartFridge: take(product : Product) : void
VirtualSmartFridge -> CU_PP_Tomar_Producto : <<include>>
|||

@enduml