@startuml

hide footbox
header CU_CR Flujo Normal
autonumber

Customer -> VirtualSmartFridge: close() : void
activate VirtualSmartFridge

VirtualSmartFridge -> FridgeDoor : close() : void
activate FridgeDoor

FridgeDoor -> FridgeDoor : stopTimer() : void

autonumber stop
FridgeDoor --> VirtualSmartFridge

autonumber resume
VirtualSmartFridge -> CU_IP_Identificar_Producto : <<include>>

autonumber stop
CU_IP_Identificar_Producto --> VirtualSmartFridge : identification result
VirtualSmartFridge -> Status : save(identificationStatus : StatusEntry)
Status --> VirtualSmartFridge : identification status
VirtualSmartFridge --> Customer : identification status

autonumber resume
Customer -> VirtualSmartFridge : retainStatus(statusId : StatusId) : void
VirtualSmartFridge -> Status : retain(statusId : StatusId) : void

autonumber stop
Status --> VirtualSmartFridge
VirtualSmartFridge --> Customer
|||

@enduml