name: Export repository and wiki documentation to latex and pdf

on: push

jobs:
  export_docs:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output  # create output dir
          # this will include README.md and any other .md file within the repository root
          echo "::set-env name=ROOT_MD_LIST::$(printf '"%s" ' *.md)"
          git clone https://github.com/mgardos/vsfridge.wiki.git
          echo "::set-env name=WIKI_MD_LIST::$(printf '"%s" ' vsfridge.wiki/*.md)"
      - name: Set up python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: docker://pandoc/latex:2.9.2.1
        with:
          args: --standalone --pdf-engine=xelatex -V geometry:top=18mm -V geometry:left=18mm -V geometry:paperwidth=210mm -V geometry:paperheight=297mm -V fontsize=10pt -f markdown-implicit_figures --output=output/readme.pdf ${{ env.ROOT_MD_LIST }}
      - uses: docker://pandoc/latex:2.9.2.1
        with:
          args: --standalone --pdf-engine=xelatex --output=output/02_vsfridge-detailed-design-architecture.tex "vsfridge.wiki/02_vsfridge-detailed-design-architecture.md"
      - uses: docker://pandoc/latex:2.9.2.1
        with:
          args: --standalone --pdf-engine=xelatex --output=output/03_vsfridge-detailed-design-architecture-core.tex "vsfridge.wiki/03_vsfridge-detailed-design-architecture-core.md"
      - uses: docker://pandoc/latex:2.9.2.1
        with:
          args: --standalone --pdf-engine=xelatex --output=output/05_vsfridge-detailed-design-architecture-emu.tex "vsfridge.wiki/05_vsfridge-detailed-design-architecture-emu.md"
      - uses: docker://pandoc/latex:2.9.2.1
        with:
          args: --standalone --pdf-engine=xelatex --output=output/06_vsfridge-detailed-design-architecture-assembly.tex "vsfridge.wiki/06_vsfridge-detailed-design-architecture-assembly.md"
      - uses: docker://pandoc/latex:2.9.2.1
        with:
          args: --standalone --pdf-engine=xelatex --output=output/09_vsfridge-implementation-model-food-identification.tex "vsfridge.wiki/09_vsfridge-implementation-model-food-identification.md"
      - uses: docker://pandoc/latex:2.9.2.1
        with:
          args: --standalone --pdf-engine=xelatex --output=output/vsfridge-test-cases.tex "vsfridge.wiki/vsfridge-test-cases.md"
      - uses: docker://pandoc/latex:2.9.2.1
        with:
          args: --standalone --pdf-engine=xelatex --output=output/vsfridge-test-cases-data.tex "vsfridge.wiki/vsfridge-test-cases-data.md"
      - uses: docker://pandoc/latex:2.9.2.1
        with:
          args: --standalone --pdf-engine=xelatex --output=output/vsfridge-test-cases-definition-add-one-food.tex "vsfridge.wiki/vsfridge-test-cases-definition-add-one-food.md"
      - uses: docker://pandoc/latex:2.9.2.1
        with:
          args: --standalone --pdf-engine=xelatex --output=output/vsfridge-test-cases-definition-add-several-food.tex "vsfridge.wiki/vsfridge-test-cases-definition-add-several-food.md"
      #- uses: docker://pandoc/latex:2.9.2.1
      #  with:
      #    args: --pdf-engine=pdflatex --template=src/site/resources/export/report.tex --output=output/report.pdf
      #- uses: docker://pandoc/latex:2.9.2.1
      #  with:
      #    args: --css=src/site/resources/export/style.css --self-contained --output=output/readme.html ${{ env.ROOT_MD_LIST }}
      - name: Process generated tex 
        run: python src/site/resources/export/tex_processor.py -i output/02_vsfridge-detailed-design-architecture.tex -o output/02_vsfridge-detailed-design-architecture_custom.tex
      - uses: actions/upload-artifact@master
        with:
          name: export-docs
          path: output
